[package]
name = "archivindex-archiver-cli"
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
publish = false

[[bin]]
name = "archivindex-archiver"
path = "src/main.rs"
# Avoid a rustdoc output-filename collision with the `archivindex-archiver` library crate.
doc = false

[dependencies]
archivindex-archiver = { version = "0.1.0", path = "../archiver/" }
archivindex-packager = { version = "0.1.0", path = "../packager/" }
cli-helpers.workspace = true
indicatif.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
