[package]
name = "archivindex-packager"
description = "Packaging WARC captures as indexed WACZ distributions"
authors.workspace = true
repository.workspace = true
documentation = "https://docs.rs/crate/archivindex-packager/"
keywords = ["warc", "wacz", "web", "archive"]
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
archivindex-surt = { version = "0.1.0", path = "../surt/" }
archivindex-wacz = { version = "0.1.0", path = "../wacz/" }
archivindex-warc = { workspace = true, features = ["gzip", "http"] }
chrono.workspace = true
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
archivindex-archiver = { version = "0.1.0", path = "../archiver/" }
chrono.workspace = true
flate2.workspace = true
