[package]
name = "archivindex-cdx"
description = "Data models for classic CDX, CDXJ, and Wayback Machine CDX JSON"
authors.workspace = true
repository.workspace = true
documentation = "https://docs.rs/crate/archivindex-cdx/"
keywords = ["cdx", "cdxj", "warc", "web", "archive"]
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true

[features]
## `bounded_static` implementations for borrowed CDX models.
bounded-static = ["dep:bounded-static"]

[dependencies]
bounded-static = { version = "0.8", optional = true }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest = "1"
test-strategy = "0.4"
